name: pr_checker
on:
  pull_request_target:
    types:
    - opened
    - edited
    - synchronize
    - labeled
    - unlabeled
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: thehanimo/pr-title-checker@e914bff8ab5e6f1a6a270da6954cd6bfd1d7f1fb  # v1.3.5
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        pass_on_octokit_error: false
        configuration_path: .github/pr-title-checker-config.json