name: pr_checker
on:
  pull_request_target:
    types:
    - opened
    - edited
    - synchronize
    - labeled
    - unlabeled
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: thehanimo/pr-title-checker@cdafc664bf9b25678d4e6df76ff67b2fe21bb5d2  # v1.3.7
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        pass_on_octokit_error: false
        configuration_path: .github/pr-title-checker-config.json